package BitcoinEcon;

import java.awt.Dimension;
import java.awt.Point;
import java.util.ArrayList;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class Market extends ViewableDigraph {
    private ArrayList<Agent> agents; // List of agents
    private int Nt; // Total number of agents
    private OrderBook orderBook;
    
    public Market() {
        super("Market");

        Nt = 30000;
        agents = new ArrayList<Agent>();
        orderBook = new OrderBook();
        
        for (int i = 0; i < Nt; i++) {
            // Only let the first few agent enter at initialization
            boolean enterMarket = false;
            if (i <= 16)
                enterMarket = true;
            
            Agent agent = new Agent("Agent" + i, i, 0, 0, enterMarket);
            agents.add(agent);
            
            add(agent);
        }
        add(orderBook);
        
        addOutport("outBitcoins");
/*
        addCoupling(Requester, "outGreen", MSD, "inGreen");
        addCoupling(Requester, "outRed", MSD, "inRed");

        addCoupling(MSD, "outGreen", this, "outGreen");
        addCoupling(MSD, "outRed", this, "outRed");*/
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 145);
        ((ViewableComponent)withName("MSD")).setPreferredLocation(new Point(240, 50));
        ((ViewableComponent)withName("Requester")).setPreferredLocation(new Point(27, 50));
    }
}
