package BitcoinEcon;

import java.awt.Dimension;
import java.awt.Point;
import java.util.ArrayList;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class Market extends ViewableDigraph {
    private ArrayList<Agent> agents; // List of agents
    private int Nt; // Total number of agents
    private OrderBook orderBook;
    private MultiServer multiServer;

    private final int NUMBER_OF_INITIAL_TRADERS = 160;
    private final int TOTAL_NUMBER_OF_TRADERS = 39649; // Total number of traders at the end of simulation
    private final double INITIAL_BITCOINS_OF_INITIAL_TRADERS = 87.28;
    private final double INITIAL_BITCOIN_PRICE = 0.0649; // The average price as of September 2010

    public Market() {
        super("Market");

        multiServer = new MultiServer("Multiserver", TOTAL_NUMBER_OF_TRADERS, NUMBER_OF_INITIAL_TRADERS,
                INITIAL_BITCOINS_OF_INITIAL_TRADERS, INITIAL_BITCOIN_PRICE);
        orderBook = new OrderBook();

        addOutport("inBitcoinPrice");
        addOutport("inTimer");

        addOutport("outTransactions");

        add(multiServer);
        add(orderBook); // Add the Model Book to the Market model

        addCoupling(this, "inBitcoinPrice", multiServer, "inBitcoinPrice");
        addCoupling(this, "inTimer", multiServer, "inTimer");

        addCoupling(multiServer, "outOrders", orderBook, "InOrders");

    }

    public static long now() {
        return System.currentTimeMillis();
    }

    /**
     * Automatically generated by the SimView program. Do not edit this manually, as
     * such changes will get overwritten.
     */
    public void layoutForSimView() {
        preferredSize = new Dimension(591, 145);
        ((ViewableComponent) withName("MSD")).setPreferredLocation(new Point(240, 50));
        ((ViewableComponent) withName("Requester")).setPreferredLocation(new Point(27, 50));
    }
}
