package BitcoinEcon;

import java.awt.*;
import java.util.*;

import BitcoinEcon.Agent.AgentType;
import GenCol.*;

import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;

public class MultiServer extends ViewableDigraph {

    private MultiServer() {
        this("Multiserver", 0, 0, 0.0, 0.0);
    }

    public MultiServer(String name, int totalNumberTraders, int numberInitialTraders,
            double initialBitcoinsInitialTraders, double initialBitcoinPrice) {
        super(name);
        make(totalNumberTraders, numberInitialTraders, initialBitcoinsInitialTraders, initialBitcoinPrice);

        // TODO - add test inputs
    }

    private void make(int totalNumberTraders, int numberInitialTraders, double initialBitcoinsInitialTraders,
            double initialBitcoinPrice) {

        addInport("inTransactions");
        addInport("inBitcoinPrice");
        addInport("inTimer");

        addInport("outOrders");
        addInport("outHashRates");
        addInport("outBitcoins");

        MultiServerCoord co = new MultiServerCoord("MultiSco");
        add(co);

        for (int i = 1; i <= totalNumberTraders; i++) {
            Agent p = new Agent(AgentType.NONE, i, initialBitcoinsInitialTraders, initialBitcoinPrice, false);
            add(p);
            co.add_procs(p);
            p.setPreferredLocation(new Point(187, 22 + 80 * (i - 1)));
        }

        Iterator i = getComponents().iterator();
        while (i.hasNext()) {
            entity ent = (entity) i.next();
            devs agent = (devs) ent;
            if (!ent.equals(co)) {
                addCoupling(co, "outTransactions", agent, "inTransactions"); // use name for routing
                addCoupling(co, "outBitcoinPrice", agent, "inBitcoinPrice"); // use name for routing
                addCoupling(co, "outTimer", agent, "inTimer"); // use name for routing

                addCoupling(agent, "outOrders", co, "inOrders");
                
                addCoupling(agent, "outHashRates", this, "outHashRates"); // This port will go to Transduder
                addCoupling(agent, "outBitcoins", this, "outBitcoins"); // This port will go to Transduder
            }

        }
        addCoupling(this, "inTransactions", co, "inTransactions");
        addCoupling(this, "inBitcoinPrice", co, "inBitcoinPrice");
        addCoupling(this, "inTimer", co, "inTimer");

        addCoupling(co, "outOrders", this, "outOrders");

        initialize();

        preferredSize = new Dimension(508, 32 + 80 * totalNumberTraders);
        co.setPreferredLocation(new Point(-7, 20));
    }

    /**
     * Automatically generated by the SimView program. Do not edit this manually, as
     * such changes will get overwritten.
     */
    public void layoutForSimView() {
        preferredSize = new Dimension(500, 252);
        ((ViewableComponent) withName("processor_3")).setPreferredLocation(new Point(201, 103));
        ((ViewableComponent) withName("MultiSco")).setPreferredLocation(new Point(-7, 20));
        ((ViewableComponent) withName("processor_1")).setPreferredLocation(new Point(187, 22));
        ((ViewableComponent) withName("processor_4")).setPreferredLocation(new Point(148, 179));
        ((ViewableComponent) withName("processor_2")).setPreferredLocation(new Point(-4, 105));
        /*
         * ((ViewableComponent)withName("processor_3")).setPreferredLocation(new
         * Point(201, 103));
         * ((ViewableComponent)withName("processor_5")).setPreferredLocation(new
         * Point(-7, 20));
         * ((ViewableComponent)withName("processor_6")).setPreferredLocation(new
         * Point(187, 22));
         * ((ViewableComponent)withName("processor_7")).setPreferredLocation(new
         * Point(148, 179));
         * ((ViewableComponent)withName("processor_8")).setPreferredLocation(new
         * Point(-4, 105));
         * ((ViewableComponent)withName("processor_9")).setPreferredLocation(new
         * Point(187, 22));
         * ((ViewableComponent)withName("processor_10")).setPreferredLocation(new
         * Point(148, 179));
         * ((ViewableComponent)withName("processor_11")).setPreferredLocation(new
         * Point(-4, 105));
         * ((ViewableComponent)withName("processor_12")).setPreferredLocation(new
         * Point(201, 103));
         * ((ViewableComponent)withName("processor_13")).setPreferredLocation(new
         * Point(-7, 20));
         * ((ViewableComponent)withName("processor_14")).setPreferredLocation(new
         * Point(187, 22));
         * ((ViewableComponent)withName("processor_15")).setPreferredLocation(new
         * Point(148, 179));
         * ((ViewableComponent)withName("processor_16")).setPreferredLocation(new
         * Point(-4, 105));
         */

    }
}
