package BitcoinEcon;

import java.awt.Dimension;
import java.awt.Point;
import java.util.ArrayList;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class OrderBook extends ViewableDigraph {

    public OrderBook() {
        super("OrderBook");

    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 145);
        ((ViewableComponent)withName("MSD")).setPreferredLocation(new Point(240, 50));
        ((ViewableComponent)withName("Requester")).setPreferredLocation(new Point(27, 50));
    }
}
